import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import Groq from 'groq-sdk';
import { OAuth2Client } from 'google-auth-library';
import User from './models/User.js';
import Project from './models/Project.js';
import OTP from './models/OTP.js';
import nodemailer from 'nodemailer';
import { randomInt } from 'crypto';

dotenv.config({ path: './.env' });

const app = express();
app.use(cors());
app.use(express.json());

// Security Headers for Google OAuth
app.use((req, res, next) => {
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin-allow-popups');
  next();
});

// Nodemailer setup
const transporter = nodemailer.createTransport({
  service: process.env.EMAIL_SERVICE || 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const sendOTPEmail = async (email, otp) => {
  const mailOptions = {
    from: `"Vibrantz AI" <${process.env.EMAIL_USER}>`,
    to: email,
    subject: 'Your Verification Code',
    text: `Your OTP for Vibrantz AI is: ${otp}. It expires in 10 minutes.`,
    html: `
      <div style="font-family: 'Courier New', Courier, monospace; background-color: #0a0a0a; color: #ffffff; padding: 40px; border-radius: 12px; border: 1px solid #333;">
        <h2 style="color: #00ff88; border-bottom: 2px solid #00ff88; padding-bottom: 10px;">VIBRANTZ AI</h2>
        <p style="font-size: 16px;">System verification required.</p>
        <div style="background-color: #1a1a1a; padding: 20px; border-radius: 8px; text-align: center; margin: 30px 0;">
          <span style="font-size: 32px; letter-spacing: 10px; font-weight: bold; color: #00ff88;">${otp}</span>
        </div>
        <p style="color: #888; font-size: 14px;">This code expires in 10 minutes. If you did not request this, please ignore this email.</p>
        <div style="margin-top: 40px; font-size: 12px; color: #444;">
          AUTOGENERATED_SYSTEM_MAIL_ARCHITECT_PROTOCOL_V1
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
  } catch (err) {
    console.error('Email sending failed:', err);
    throw new Error('Failed to send verification email');
  }
};

// Request Logger
app.use((req, res, next) => {
  console.log(`${new Date().toISOString()} - ${req.method} ${req.url}`);
  next();
});

const groq = new Groq({
  apiKey: process.env.VITE_GROQ_API_KEY,
});

const client = new OAuth2Client(process.env.VITE_GOOGLE_CLIENT_ID);

mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('MongoDB connection error:', err));

app.get('/api/health', (req, res) => res.json({ status: 'ok' }));

// Middleware to verify JWT
const authenticate = (req, res, next) => {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'Unauthorized' });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.userId = decoded.userId;
    next();
  } catch (err) {
    res.status(401).json({ error: 'Invalid token' });
  }
};

// Auth Routes
app.post('/api/auth/send-otp', async (req, res) => {
  try {
    const { email, type } = req.body;
    if (!email) throw new Error('Email is required');

    if (type === 'register') {
      const existingUser = await User.findOne({ email });
      if (existingUser) throw new Error('User already exists');
    } else if (type === 'forgot_password') {
      const existingUser = await User.findOne({ email });
      if (!existingUser) throw new Error('User not found');
    }

    const otp = randomInt(100000, 999999).toString();
    await OTP.deleteOne({ email, type });
    await new OTP({ email, otp, type }).save();

    await sendOTPEmail(email, otp);
    res.json({ message: 'OTP sent successfully' });
  } catch (err) {
    console.error('OTP Error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/register', async (req, res) => {
  try {
    const { email, password, otp } = req.body;
    if (!email || !password || !otp) throw new Error('All fields are required');

    const otpRecord = await OTP.findOne({ email, otp, type: 'register' });
    if (!otpRecord) throw new Error('Invalid or expired OTP');

    const user = new User({ email, password });
    await user.save();

    await OTP.deleteOne({ _id: otpRecord._id });

    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Registration error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/forgot-password-reset', async (req, res) => {
  try {
    const { email, otp, newPassword } = req.body;
    if (!email || !otp || !newPassword) throw new Error('All fields are required');

    const otpRecord = await OTP.findOne({ email, otp, type: 'forgot_password' });
    if (!otpRecord) throw new Error('Invalid or expired OTP');

    const user = await User.findOne({ email });
    if (!user) throw new Error('User not found');

    user.password = newPassword;
    await user.save();

    await OTP.deleteOne({ _id: otpRecord._id });

    res.json({ message: 'Password updated successfully' });
  } catch (err) {
    console.error('Reset error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user || !(await user.comparePassword(password))) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }
    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Login error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/google', async (req, res) => {
  try {
    const { credential } = req.body;
    const ticket = await client.verifyIdToken({
      idToken: credential,
      audience: process.env.VITE_GOOGLE_CLIENT_ID,
    });
    const { email, sub: googleId } = ticket.getPayload();

    let user = await User.findOne({
      $or: [{ googleId }, { email }]
    });

    if (!user) {
      user = new User({ email, googleId });
      await user.save();
    } else if (!user.googleId) {
      user.googleId = googleId;
      await user.save();
    }

    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Google Auth error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.get('/api/auth/me', authenticate, async (req, res) => {
  const user = await User.findById(req.userId).select('-password');
  res.json({ user: { id: user._id, email: user.email } });
});

// Project Routes
app.get('/api/projects', authenticate, async (req, res) => {
  const projects = await Project.find({ userId: req.userId }).sort({ createdAt: -1 });
  res.json(projects.map(p => ({ ...p._doc, id: p._id })));
});

app.post('/api/projects', authenticate, async (req, res) => {
  try {
    const { title, projectIdea, description, level, duration, workflow, techStack } = req.body;
    const project = new Project({
      userId: req.userId,
      title,
      projectIdea,
      description,
      level,
      duration,
      workflow,
      techStack,
      status: 'generating'
    });
    await project.save();
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/ai/suggest-workflow', authenticate, async (req, res) => {
  try {
    const { description, level, duration } = req.body;

    const prompt = `Perform a deep domain analysis for a project with the following description:
    Description: ${description}
    Target Complexity Level: ${level}
    Intended Timeline: ${duration}
    
    Requirements:
    1. Outline how the project can be approached and the steps involved in creating it.
    2. For EACH step, provide a "title" and a "brief" (what and how will be done).
    3. Ensure the steps are logical, sequential, and specific to the project.
    4. The number of steps should be realistic for the "${duration}" timeline and "${level}" level.

    The output MUST be a VALID JSON object with a single key "workflow" containing an array of objects:
    {
      "workflow": [
        { "title": "Step Title", "brief": "Small brief about what and how will be done" }
      ]
    }
    
    Return ONLY the JSON object. No preamble or explanations.`;

    const response = await groq.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: 'You are an Expert Project Architect. Your goal is to engineer a realistic, domain-specific execution roadmap. Return ONLY a JSON object.'
        },
        { role: 'user', content: prompt },
      ],
      model: 'llama-3.3-70b-versatile',
      response_format: { type: "json_object" }
    });

    const content = response.choices[0]?.message?.content || '{"workflow": []}';
    const parsed = JSON.parse(content);
    res.json({ workflow: parsed.workflow || [] });
  } catch (err) {
    console.error('Workflow Suggestion Error:', err);
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/ai/suggest-techstack', authenticate, async (req, res) => {
  try {
    const { description, workflow, level } = req.body;

    const prompt = `Analyze the project idea deeply and suggest a highly used technology stack.
    Description: ${description}
    Workflow: ${JSON.stringify(workflow)}
    Project Level: ${level}
    
    Modules to analyze and suggest tech for: 
    - Signup/Login (Auth)
    - Frontend
    - Backend
    - API (Communication/Protocol)
    - Database
    - Payment (if relevant)
    - Any other critical modules for this specific project

    For EACH module:
    1. Suggest a highly used/industry-standard technology.
    2. Provide a short, professional reason why this specific tech is recommended for this project.
    
    The output MUST be a VALID JSON object with a single key "techStack" containing an array of objects:
    {
      "techStack": [
        { "module": "Module Name", "tech": "Technology Name", "reason": "Specific logical reason" }
      ]
    }
    
    Return ONLY the JSON object. No preamble or explanations.`;

    const response = await groq.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: 'You are a Senior Technology Architect. You MUST return a valid JSON object with a "techStack" key containing the recommendations.'
        },
        { role: 'user', content: prompt },
      ],
      model: 'llama-3.3-70b-versatile',
      response_format: { type: "json_object" }
    });

    const content = response.choices[0]?.message?.content || '{"techStack": []}';
    const parsed = JSON.parse(content);
    res.json({ techStack: parsed.techStack || [] });
  } catch (err) {
    console.error('Tech Stack Suggestion Error:', err);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/projects/:id', authenticate, async (req, res) => {
  try {
    const project = await Project.findOne({ _id: req.params.id, userId: req.userId });
    if (!project) return res.status(404).json({ error: 'Project not found' });
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

app.patch('/api/projects/:id', authenticate, async (req, res) => {
  try {
    const project = await Project.findOneAndUpdate(
      { _id: req.params.id, userId: req.userId },
      req.body,
      { new: true }
    );
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// AI Generation Route (Streaming)
app.post('/api/generate', authenticate, async (req, res) => {
  const { projectIdea, projectId } = req.body;

  try {
    const project = await Project.findById(projectId);
    if (!project) return res.status(404).json({ error: 'Project not found' });

    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    const SYSTEM_PROMPT = `You are an advanced AI Project Architect. Your role is to convert a user's project idea into a complete, structured, execution-ready architecture blueprint.
    
  Additional Context:
  - Project Level: ${project.level || 'Not specified'}
  - Project Duration: ${project.duration || 'Not specified'}
  - Final Workflow: ${JSON.stringify(project.workflow || [])}
  - Selected Tech Stack: ${JSON.stringify(project.techStack || [])}
  - Description: ${project.description || 'Not specified'}

  You MUST output a valid JSON object with the following structure:
  {
    "projectAnalysis": {
      "objective": "string",
      "type": "string",
      "complexity": "beginner|intermediate|advanced"
    },
    "roadmap": [
      {
        "phase": "string (e.g. Phase 1: Authentication & User Roles)",
        "description": "Comprehensive overview of this phase's goals",
        "milestones": [
          {
            "id": "string (unique)",
            "title": "string",
            "concept": "The technical concept (e.g. JWT, RBAC, Schema Design)",
            "practicalExample": "A CONCRETE code snippet using the SELECTED TECH (e.g. a React component, a Node.js route, or a Mongoose schema)",
            "documentation": {
              "tool": "The specific technology from the techStack for this step",
              "rationale": "Why this specific tool is used for this specific project feature",
              "quickStart": "Command or code to initialize/use this tool in this context"
            },
            "guidedSteps": ["Granular, low-level implementation instructions"],
            "verification": "Exactly how to test this specific feature"
          }
        ]
      }
    ],
    "folderStructure": "string (detailed folder tree based on the tech stack)",
    "technicalOverview": "A deep-dive technical summary of how all modules (Auth, Admin, Dashboards, DB) interact."
  }

  STRICT INSTRUCTIONS:
  1. ADHERENCE: You MUST use the "Selected Approach/Workflow" and "Selected Tech Stack" provided below. Do NOT suggest generic alternatives.
  2. GRANULARITY: If the workflow mentions "Admin Dashboard" or "Student Sections", you MUST create specific milestones for each of those features.
  3. INTEGRATED DOCS: Provide exhaustive documentation for every tool mentioned in the tech stack.
  4. SEQUENTIAL: Start from initialization (npm init/vite create) and end with deployment.
  5. EXAMPLES: Practical examples must be usable, non-placeholder code snippets.

  IMPORTANT: Return ONLY the JSON object. No markdown, no preamble. Use "\\\\n" for newlines.
  The JSON MUST be perfectly valid. Avoid raw newlines in string values.`;

    const stream = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: `Project Idea: ${projectIdea}\nWorkflow to follow: ${JSON.stringify(project.workflow)}\n\nGenerate a complete project architecture blueprint based on this specific workflow and idea.` },
      ],
      model: 'llama-3.3-70b-versatile',
      stream: true,
    });

    let fullText = '';
    for await (const chunk of stream) {
      const content = chunk.choices[0]?.delta?.content || '';
      fullText += content;
      res.write(`data: ${JSON.stringify({ choices: [{ delta: { content } }] })}\n\n`);
    }

    res.write('data: [DONE]\n\n');
    res.end();
  } catch (err) {
    console.error('Generation error:', err);
    res.write(`data: ${JSON.stringify({ error: err.message })}\n\n`);
    res.end();
  }
});

app.use((req, res) => {
  console.log('UNMATCHED REQUEST:', req.method, req.url);
  res.status(404).json({ error: `Route ${req.method} ${req.url} not found` });
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
