import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import Groq from 'groq-sdk';
import { OAuth2Client } from 'google-auth-library';
import User from './models/User.js';
import Project from './models/Project.js';
import OTP from './models/OTP.js';
import nodemailer from 'nodemailer';
import { randomInt } from 'crypto';

dotenv.config({ path: './.env' });

const app = express();
app.use(cors());
app.use(express.json());

// Security Headers for Google OAuth
app.use((req, res, next) => {
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin-allow-popups');
  next();
});

// Nodemailer setup
const transporter = nodemailer.createTransport({
  service: process.env.EMAIL_SERVICE || 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const sendOTPEmail = async (email, otp) => {
  const mailOptions = {
    from: `"Vibrantz AI" <${process.env.EMAIL_USER}>`,
    to: email,
    subject: 'Your Verification Code',
    text: `Your OTP for Vibrantz AI is: ${otp}. It expires in 10 minutes.`,
    html: `
      <div style="font-family: 'Courier New', Courier, monospace; background-color: #0a0a0a; color: #ffffff; padding: 40px; border-radius: 12px; border: 1px solid #333;">
        <h2 style="color: #00ff88; border-bottom: 2px solid #00ff88; padding-bottom: 10px;">VIBRANTZ AI</h2>
        <p style="font-size: 16px;">System verification required.</p>
        <div style="background-color: #1a1a1a; padding: 20px; border-radius: 8px; text-align: center; margin: 30px 0;">
          <span style="font-size: 32px; letter-spacing: 10px; font-weight: bold; color: #00ff88;">${otp}</span>
        </div>
        <p style="color: #888; font-size: 14px;">This code expires in 10 minutes. If you did not request this, please ignore this email.</p>
        <div style="margin-top: 40px; font-size: 12px; color: #444;">
          AUTOGENERATED_SYSTEM_MAIL_ARCHITECT_PROTOCOL_V1
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
  } catch (err) {
    console.error('Email sending failed:', err);
    throw new Error('Failed to send verification email');
  }
};

// Request Logger
app.use((req, res, next) => {
  console.log(`${new Date().toISOString()} - ${req.method} ${req.url}`);
  next();
});

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY || process.env.VITE_GROQ_API_KEY,
});

const client = new OAuth2Client(process.env.VITE_GOOGLE_CLIENT_ID);

mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('MongoDB connection error:', err));

app.get('/api/health', (req, res) => res.json({ status: 'ok' }));

// Middleware to verify JWT
const authenticate = (req, res, next) => {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'Unauthorized' });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.userId = decoded.userId;
    next();
  } catch (err) {
    res.status(401).json({ error: 'Invalid token' });
  }
};

// Auth Routes
app.post('/api/auth/send-otp', async (req, res) => {
  try {
    const { email, type } = req.body;
    if (!email) throw new Error('Email is required');

    if (type === 'register') {
      const existingUser = await User.findOne({ email });
      if (existingUser) throw new Error('User already exists');
    } else if (type === 'forgot_password') {
      const existingUser = await User.findOne({ email });
      if (!existingUser) throw new Error('User not found');
    }

    const otp = randomInt(100000, 999999).toString();
    await OTP.deleteOne({ email, type });
    await new OTP({ email, otp, type }).save();

    await sendOTPEmail(email, otp);
    res.json({ message: 'OTP sent successfully' });
  } catch (err) {
    console.error('OTP Error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/register', async (req, res) => {
  try {
    const { email, password, otp } = req.body;
    if (!email || !password || !otp) throw new Error('All fields are required');

    const otpRecord = await OTP.findOne({ email, otp, type: 'register' });
    if (!otpRecord) throw new Error('Invalid or expired OTP');

    const user = new User({ email, password });
    await user.save();

    await OTP.deleteOne({ _id: otpRecord._id });

    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Registration error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/forgot-password-reset', async (req, res) => {
  try {
    const { email, otp, newPassword } = req.body;
    if (!email || !otp || !newPassword) throw new Error('All fields are required');

    const otpRecord = await OTP.findOne({ email, otp, type: 'forgot_password' });
    if (!otpRecord) throw new Error('Invalid or expired OTP');

    const user = await User.findOne({ email });
    if (!user) throw new Error('User not found');

    user.password = newPassword;
    await user.save();

    await OTP.deleteOne({ _id: otpRecord._id });

    res.json({ message: 'Password updated successfully' });
  } catch (err) {
    console.error('Reset error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user || !(await user.comparePassword(password))) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }
    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Login error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.post('/api/auth/google', async (req, res) => {
  try {
    const { credential } = req.body;
    const ticket = await client.verifyIdToken({
      idToken: credential,
      audience: process.env.VITE_GOOGLE_CLIENT_ID,
    });
    const { email, sub: googleId } = ticket.getPayload();

    let user = await User.findOne({
      $or: [{ googleId }, { email }]
    });

    if (!user) {
      user = new User({ email, googleId });
      await user.save();
    } else if (!user.googleId) {
      user.googleId = googleId;
      await user.save();
    }

    const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET);
    res.json({ token, user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Google Auth error:', err);
    res.status(400).json({ error: err.message });
  }
});

app.get('/api/auth/me', authenticate, async (req, res) => {
  const user = await User.findById(req.userId).select('-password');
  res.json({ user: { id: user._id, email: user.email } });
});

// Project Routes
app.get('/api/projects', authenticate, async (req, res) => {
  const projects = await Project.find({ userId: req.userId }).sort({ createdAt: -1 });
  res.json(projects.map(p => ({ ...p._doc, id: p._id })));
});

app.post('/api/projects', authenticate, async (req, res) => {
  try {
    const { title, projectIdea, description, level, duration, workflow, techStack } = req.body;
    const project = new Project({
      userId: req.userId,
      title,
      projectIdea,
      description,
      level,
      duration,
      workflow,
      techStack,
      status: 'generating'
    });
    await project.save();
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// Helper function to call Groq API with robust model fallback and error handling
const callGroqWithFallback = async (messages, responseFormat = { type: 'json_object' }) => {
  let models = [
    'groq/compound-mini',
    'groq/compound',
    'qwen/qwen3.6-27b',
    'allam-2-7b',
    'openai/gpt-oss-20b'
  ];

  try {
    const listRes = await groq.models.list();
    if (listRes && Array.isArray(listRes.data) && listRes.data.length > 0) {
      const activeModels = listRes.data
        .map(m => m.id)
        .filter(id => !id.includes('whisper') && !id.includes('guard') && !id.includes('orpheus'));
      if (activeModels.length > 0) {
        console.log(`[Groq AI] Active chat models for key:`, activeModels);
        models = [...new Set([...activeModels, ...models])];
      }
    }
  } catch (e) {
    console.warn(`[Groq AI] Model list query fallback:`, e.message);
  }

  let lastError = null;

  for (const model of models) {
    try {
      console.log(`[Groq AI] Attempting model: ${model}`);
      // Only attach response_format if the model supports JSON mode or test call
      const options = {
        messages,
        model,
      };
      if (responseFormat) {
        options.response_format = responseFormat;
      }
      
      const response = await groq.chat.completions.create(options);
      console.log(`[Groq AI] Success using model: ${model}`);
      return response;
    } catch (err) {
      console.warn(`[Groq AI] Model ${model} failed (${err.status || err.code}): ${err.message}`);
      lastError = err;
      if (err.status === 404 || err.status === 400 || err.status === 429) {
        continue;
      }
      break;
    }
  }

  throw lastError;
};

app.post('/api/ai/suggest-workflow', authenticate, async (req, res) => {
  try {
    const { description, level, duration } = req.body;

    if (!description || !description.trim()) {
      return res.status(400).json({ error: 'Project description is required' });
    }

    const prompt = `You are Vibrantz.AI's Chief AI Systems Architect.
    Domain-Specific Rule: Do NOT default to generic MERN web stack. Tailor directly to: "${description}".
    (e.g., 3D Game -> 3D engine, physics, loop, assets; AI -> pipeline, embeddings, inference; Mobile -> screens, native APIs; Web -> SPA, API, DB).

    Project Complexity: ${level || 'standard'} | Timeline: ${duration || 'flexible'}

    Generate a CRISP, COMPACT 5-stage building roadmap:
    - Stage 0: Environment & Setup (Repo init, domain access & baseline configs)
    - Stage 1: Core Interface & Viewport (Main UI / 3D viewport / screens & state)
    - Stage 2: Core Domain Logic & Engine (Domain processing logic, controllers & event loop)
    - Stage 3: Data Layer & Persistence (Schemas, models, assets & persistent storage)
    - Stage 4: Testing & Production Deployment (QA, cloud hosting & CI/CD)

    RULES FOR "brief":
    - Keep each brief COMPACT (2-3 concise sentences max).
    - Outline: (1) Core build task, (2) UI/Viewport element, (3) Data/Event flow.
    - Avoid verbose essays.

    The output MUST be a VALID JSON object with a single key "workflow" containing an array of 5 objects:
    {
      "workflow": [
        { 
          "title": "Stage 0: Environment & Setup", 
          "brief": "Initialize project repository and domain dependencies. Configure access control and baseline environment variables." 
        }
      ]
    }
    
    Return ONLY the JSON object. No preamble or markdown wrapping.`;

    const messages = [
      {
        role: 'system',
        content: 'You are an Expert Domain Architect. Generate a crisp, compact, domain-specific execution roadmap. Return ONLY valid JSON.'
      },
      { role: 'user', content: prompt }
    ];

    const response = await callGroqWithFallback(messages, { type: 'json_object' });
    const content = response.choices[0]?.message?.content || '{"workflow": []}';
    const parsed = JSON.parse(content);

    return res.json({ workflow: parsed.workflow || [] });
  } catch (err) {
    console.error('Workflow Suggestion Error:', err);

    if (err.status === 401 || err.code === 'invalid_api_key') {
      return res.status(401).json({ error: 'Invalid Groq API Key. Please verify your VITE_GROQ_API_KEY / GROQ_API_KEY environment variable.' });
    }

    return res.status(err.status || 500).json({
      error: err.message || 'An error occurred while generating project workflow'
    });
  }
});

app.post('/api/ai/suggest-techstack', authenticate, async (req, res) => {
  try {
    const { description, workflow, level } = req.body;

    const prompt = `You are Vibrantz.AI's Lead Technical Architect. Perform an intelligent, deep domain analysis of the project below:
    
    Project Description & Vision: "${description}"
    Project Complexity: "${level}"
    Workflow Stages: ${JSON.stringify(workflow)}

    DOMAIN-SPECIFIC STACK RULES - STRICTLY ENFORCED:
    - NEVER default to generic MERN or web boilerplate if the project is in a specialized category!
    - 3D Games / Simulations (e.g. 3D car racing game, VR, RPG): Suggest Unity (C#) / Unreal Engine 5 (C++) / Three.js / React Three Fiber / WebGL / Godot / Rapier/PhysX / Colyseus / Howler.js.
    - AI / ML / Data Engineering: Suggest Python, FastAPI, PyTorch, LangChain, LlamaIndex, Vector DBs (Pinecone/Milvus/Qdrant), Celery, HuggingFace.
    - Mobile Apps: Suggest Flutter, React Native, Swift (iOS), Kotlin (Android), Supabase/Firebase.
    - High-Performance Distributed Systems: Suggest Go (Golang), Rust, gRPC, Apache Kafka, PostgreSQL, Kubernetes.
    - Full-Stack Web Applications: Suggest React / Next.js / Node.js / Express / Tailwind CSS / PostgreSQL / Redis.
    - Embedded / IoT / Hardware: Suggest C++, Rust, MQTT, ESP-IDF, FreeRTOS, InfluxDB.

    Analyze what this project SPECIFICALLY is and recommend 6-7 domain-tailored layers matching its actual requirements:
    
    For EACH layer:
    - "module": Relevant layer name for this specific domain (e.g., "Frontend / Engine", "Backend / Processing", "Database / Vector / Storage", "Auth & Security", "Specialized Libraries / SDKs", "Deployment / Cloud Host")
    - "tech": Specific high-demand industry-standard technology tailored to THIS project
    - "reason": Deep, project-specific technical rationale explaining why this exact tool is necessary for this project's mechanics/architecture
    - "customAlternatives": 1-2 realistic alternative industry tools

    The output MUST be a VALID JSON object with a single key "techStack" containing an array of objects:
    {
      "techStack": [
        { 
          "module": "Frontend / Engine", 
          "tech": "Recommended Technology", 
          "reason": "Tailored explanation for this project",
          "customAlternatives": "Alternative options"
        }
      ]
    }
    
    Return ONLY the JSON object. No preamble or markdown wrapping.`;

    const messages = [
      {
        role: 'system',
        content: 'You are a Senior Domain-Specific Technology Architect. Suggest realistic, domain-specific technology stacks tailored specifically to the project type (Gaming, AI, Mobile, Embedded, Web, or Systems). Return ONLY valid JSON.'
      },
      { role: 'user', content: prompt }
    ];

    const response = await callGroqWithFallback(messages, { type: 'json_object' });
    const content = response.choices[0]?.message?.content || '{"techStack": []}';
    const parsed = JSON.parse(content);
    res.json({ techStack: parsed.techStack || [] });
  } catch (err) {
    console.error('Tech Stack Suggestion Error:', err);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/projects/:id', authenticate, async (req, res) => {
  try {
    const project = await Project.findOne({ _id: req.params.id, userId: req.userId });
    if (!project) return res.status(404).json({ error: 'Project not found' });
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

app.patch('/api/projects/:id', authenticate, async (req, res) => {
  try {
    const project = await Project.findOneAndUpdate(
      { _id: req.params.id, userId: req.userId },
      req.body,
      { new: true }
    );
    res.json({ ...project._doc, id: project._id });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// AI Generation Route (Streaming)
app.post('/api/generate', authenticate, async (req, res) => {
  const { projectIdea, projectId } = req.body;

  try {
    const project = await Project.findById(projectId);
    if (!project) return res.status(404).json({ error: 'Project not found' });

    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    const SYSTEM_PROMPT = `You are Vibrantz.AI's Chief AI Architect and Technical Educator.
    Analyze the project vision and build a domain-tailored TryHackMe/GeeksforGeeks-style interactive learning roadmap.
    
    CRITICAL BEHAVIORAL RULE: NO GENERIC MERN/WEB DEFAULTS.
    - If this is a 3D Game: write rooms covering 3D Game Engine (Unity/Three.js), Game Loop, Physics, Shaders, 3D Assets, Spatial Audio, Game Servers.
    - If this is AI/ML: write rooms covering Python/FastAPI, Data Pipelines, PyTorch, Vector DBs, Embedding Models, Agent Orchestration.
    - If this is Mobile: write rooms covering React Native/Flutter, Native Device APIs, Mobile State, Push Notifications.
    - Tailor every room, code snippet, and explanation directly to: "${project.title || projectIdea}".

    Project Title: ${project.title || projectIdea}
    Project Level: ${project.level || 'Standard'}
    Target Duration: ${project.duration || 'Flexible'}
    Workflow Summary: ${JSON.stringify((project.workflow || []).map((w, i) => `${i}. ${w.title}`)) }
    Tech Stack Summary: ${JSON.stringify((project.techStack || []).map(t => `${t.module}: ${t.tech}`)) }
    
    OUTPUT FORMAT: You MUST return a VALID JSON object matching this schema:
    {
      "projectAnalysis": {
        "objective": "${project.title || 'Technical Project Architecture'}",
        "type": "Domain-Specific Architecture & Learning Blueprint",
        "complexity": "${project.level || 'Standard'}"
      },
      "techStackTable": [
        {
          "layer": "Architecture Layer",
          "recommendation": "Chosen Technology",
          "whySelected": "Specific justification for this project",
          "customAlternatives": "User Custom Alternatives"
        }
      ],
      "architectureDiagram": "ASCII or Mermaid diagram showing client, engine, processing backend, data layer & external services flow",
      "roadmap": [
        {
          "phase": "Module 0: Day-0 Environment & Authentication Setup",
          "description": "Module overview and prerequisites",
          "milestones": [
            {
              "id": "m-0-1",
              "title": "Room 0.1: Project Initialization & Domain Setup",
              "concept": "1. 📖 Concept & Theory (What & Why):\nClear plain-language explanation of why this concept is required for this specific project.",
              "implementationBlueprint": "2. 🛠️ Implementation Blueprint:\nStep-by-step logic and industry-standard pattern to implement it.",
              "practicalExample": "// 3. 💻 Project-Specific Hands-On Code\n// File: path/to/project_file.ext\n// Concrete annotated code snippet written specifically for this project",
              "documentation": {
                "tool": "Tool Name",
                "rationale": "Tool Rationale",
                "quickStart": "Command or setup script"
              },
              "guidedSteps": [
                "Step 1: Concrete guided instruction",
                "Step 2: Concrete guided instruction"
              ],
              "verification": "4. 🧪 Verification & Testing:\nConcrete instructions on how to test that this room's task works.",
              "knowledgeCheck": [
                "Completed task action 1",
                "Completed task action 2",
                "Concept Check: Comprehension self-assessment"
              ]
            }
          ]
        }
      ],
      "folderStructure": "Project directory layout suited for this tech stack",
      "technicalOverview": "Comprehensive architecture summary."
    }

    Cover 4-5 focused Modules from Day-0 Setup, Core Viewport/Engine, Backend/Processing & Data, to Testing & Cloud Deployment.
    CRITICAL: Return ONLY valid JSON. Escape internal newlines inside strings with \\\\n.`;

    const models = [
      'groq/compound-mini',
      'groq/compound',
      'qwen/qwen3.6-27b',
      'allam-2-7b',
      'openai/gpt-oss-20b'
    ];

    let stream = null;
    let selectedModel = null;
    for (const model of models) {
      try {
        console.log(`[Groq AI Stream] Initiating blueprint stream with model: ${model}`);
        stream = await groq.chat.completions.create({
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: `Project Vision: ${projectIdea}\n\nGenerate the complete interactive TryHackMe/GeeksforGeeks architecture blueprint JSON.` },
          ],
          model,
          response_format: { type: "json_object" },
          stream: true,
        });
        selectedModel = model;
        break;
      } catch (err) {
        console.warn(`[Groq AI Stream] Model ${model} failed (${err.status || err.code}): ${err.message}`);
        if (err.status === 404 || err.status === 400) continue;
        throw err;
      }
    }

    if (!stream) throw new Error("Failed to initialize AI blueprint streaming model");
    console.log(`[Groq AI Stream] Streaming from ${selectedModel}...`);

    for await (const chunk of stream) {
      const content = chunk.choices[0]?.delta?.content || '';
      if (content) {
        res.write(`data: ${JSON.stringify({ choices: [{ delta: { content } }] })}\n\n`);
      }
    }

    console.log(`[Groq AI Stream] Completed stream for ${projectId}`);
    res.write('data: [DONE]\n\n');
    res.end();
  } catch (err) {
    console.error('Generation error:', err);
    res.write(`data: ${JSON.stringify({ error: err.message })}\n\n`);
    res.end();
  }
});

app.use((req, res) => {
  console.log('UNMATCHED REQUEST:', req.method, req.url);
  res.status(404).json({ error: `Route ${req.method} ${req.url} not found` });
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
